const { ActionRowBuilder, ButtonBuilder, ButtonStyle, SlashCommandBuilder } = require('discord.js');
const { createCustomEmbed, createErrorEmbed } = require('../../utils/enhancedEmbeds');
const { User, Shift, Warning, Activity } = require('../../database/mongo');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('case_file')
        .setDescription('Generate a highly detailed relational dossier for a specific user')
        .addUserOption(opt => opt.setName('user').setDescription('The user to investigate').setRequired(true)),

    async execute(interaction) {
        try {
            await interaction.deferReply();
            const targetUser = interaction.options.getUser('user');
            const guildId = interaction.guildId;

            // Fetch user record from database
            const userRecord = await User.findOne({ userId: targetUser.id });
            const staffSync = userRecord?.guilds?.find(g => g.guildId === guildId)?.staff || {};
            if (!userRecord || !userRecord.guilds?.some(g => g.guildId === guildId)) {
                const row = new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('auto_v1_case_file').setLabel('🔄 Sync Live Data').setStyle(ButtonStyle.Secondary));
                return await interaction.editReply({ embeds: [createErrorEmbed(`No local database records exist for **${targetUser.username}** in this sector.`)], components: [row] });
            }

            // 1. Fetch exact warnings
            const warnings = await Warning.find({ userId: targetUser.id, guildId })
                .sort({ createdAt: -1 })
                .limit(3)
                .lean();

            // 2. Fetch trailing shifts
            const shifts = await Shift.find({ userId: targetUser.id, guildId })
                .sort({ startTime: -1 })
                .limit(3)
                .lean();

            // 3. Fetch trailing activities
            const activities = await Activity.find({ userId: targetUser.id, guildId })
                .sort({ createdAt: -1 })
                .limit(5)
                .lean();

            // Construct Warning String
            let warningStr = '✅ *Active Record Clean*';
            if (warnings.length > 0) {
                warningStr = warnings.map(w => {
                    const t = Math.floor(new Date(w.createdAt).getTime() / 1000);
                    return `- <t:${t}:d> | **[${w.severity.toUpperCase()}]** *${w.reason}*`;
                }).join('\n');
            }

            // Construct Shifts String
            let shiftStr = '❌ *No Logged Shifts*';
            if (shifts.length > 0) {
                shiftStr = shifts.map(s => {
                    const t = Math.floor(new Date(s.startTime).getTime() / 1000);
                    if (!s.endTime) return `- <t:${t}:R> | 🟢 **ACTIVE NOW**`;
                    const hrs = Math.floor(s.duration / 3600);
                    const mins = Math.floor((s.duration % 3600) / 60);
                    return `- <t:${t}:d> | ⏱️ \`${hrs}h ${mins}m\``;
                }).join('\n');
            }

            // Construct Activities String
            let activityStr = '❌ *No Recorded Activities*';
            if (activities.length > 0) {
                activityStr = activities.map(a => {
                    const t = Math.floor(new Date(a.createdAt).getTime() / 1000);
                    const type = a.type.toUpperCase();
                    const action = a.data?.action ? `(${a.data.action})` : '';
                    return `- <t:${t}:R> | 🔹 \`${type}\` ${action}`;
                }).join('\n');
            }

            const totalShiftTime = shifts.reduce((acc, s) => acc + (s.duration || 0), 0);
            const totalHrs = Math.floor(totalShiftTime / 3600);
            const trophies = staffSync.trophies || [];

            const embed = await createCustomEmbed(interaction, {
                title: `📁 Certified User Dossier: ${targetUser.username}`,
                thumbnail: targetUser.displayAvatarURL({ dynamic: true }),
                description: `**Dossier Reference:** \`${targetUser.id}\`\n**Current Rank:** \`${(staffSync.rank || 'trial').toUpperCase()}\` | **Point Balance:** \`${staffSync.points || 0}\``,
                footer: `Security Clearance Granted • Generated by ${interaction.user.username}`
            });

            embed.addFields(
                { name: '🚨 Recent Disciplinary Incidents', value: warningStr, inline: false },
                { name: '⏱️ Recent Operational Shifts', value: shiftStr, inline: false },
                { name: '📋 Recent Global Telemetry', value: activityStr, inline: false },
                { name: '🏅 Relational Analytics', value: `\`Lifetime Velocity:\` **${totalHrs}h**\n\`Merits Unlocked:\` **${trophies.length}**\n\`Login Streak:\` 🔥 **${staffSync.streak || 0}**`, inline: false }
            );

            const row = new ActionRowBuilder().addComponents(
                new ButtonBuilder().setCustomId(`case_notify_${targetUser.id}`).setLabel('🔔 Notify User').setStyle(ButtonStyle.Primary),
                new ButtonBuilder().setCustomId(`case_archive_${targetUser.id}`).setLabel('🗄️ Archive Lookup').setStyle(ButtonStyle.Secondary),
                new ButtonBuilder().setCustomId('auto_v1_case_file').setLabel('🔄 Sync Live Data').setStyle(ButtonStyle.Secondary)
            );
            await interaction.editReply({ embeds: [embed], components: [row] });

        } catch (error) {
            console.error('Case File Error:', error);
            const errEmbed = createErrorEmbed('An error occurred while generating the user case file.');
            if (interaction.deferred || interaction.replied) {
                const row = new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('auto_v1_case_file').setLabel('🔄 Sync Live Data').setStyle(ButtonStyle.Secondary));
                return await interaction.editReply({ embeds: [errEmbed], components: [row] });
            } else {
                await interaction.editReply({ embeds: [errEmbed], ephemeral: true });
            }
        }
    },

    async handleCaseButtons(interaction, client) {
        const { customId, guildId, guild } = interaction;
        const targetUserId = customId.split('_').pop();

        if (customId.startsWith('case_notify_')) {
            await interaction.deferReply({ ephemeral: true });
            try {
                const targetUser = await client.users.fetch(targetUserId);
                const embed = await createCustomEmbed(interaction, {
                    title: `🛡️ Security Notice: ${guild.name}`,
                    description: `**Official Notification:** A moderator has accessed your personal dossier for review.\n\n*This is an automated administrative alert. Please ensure you are following all server protocols.*`,
                    color: 'warning'
                });
                await targetUser.send({ embeds: [embed] });
                await interaction.editReply({ content: `✅ Successfully dispatched administrative notice to <@${targetUserId}>.` });
            } catch (e) {
                await interaction.editReply({ content: `❌ Failed to notify user. They may have DMs closed.` });
            }
        }
        else if (customId.startsWith('case_archive_')) {
            await interaction.deferReply({ ephemeral: true });
            const warnings = await Warning.find({ userId: targetUserId, guildId }).sort({ createdAt: -1 }).lean();

            if (!warnings.length) return interaction.editReply({ content: 'No historical records found for this user.' });

            const archiveLines = warnings.map(w => {
                const date = `<t:${Math.floor(new Date(w.createdAt).getTime() / 1000)}:d>`;
                return `• **${date}**: ${w.reason} (${w.severity})`;
            }).join('\n');

            const embed = await createCustomEmbed(interaction, {
                title: `🗄️ Historical Archive: ${targetUserId}`,
                description: `Complete record of all detected incidents:\n\n${archiveLines.substring(0, 3900)}`,
                color: 'info'
            });
            await interaction.editReply({ embeds: [embed] });
        }
    }
};


